package com.jointown.zy.common.model;

public class BreedAttr extends Record {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BREED_ATTR.ID
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BREED_ATTR.BREED_ID
     *
     * @mbggenerated
     */
    private Long breedId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BREED_ATTR.ATTR_NAME
     *
     * @mbggenerated
     */
    private String attrName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BREED_ATTR.ATTR_VALUE
     *
     * @mbggenerated
     */
    private String attrValue;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BREED_ATTR.ID
     *
     * @return the value of BREED_ATTR.ID
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BREED_ATTR.ID
     *
     * @param id the value for BREED_ATTR.ID
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BREED_ATTR.BREED_ID
     *
     * @return the value of BREED_ATTR.BREED_ID
     *
     * @mbggenerated
     */
    public Long getBreedId() {
        return breedId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BREED_ATTR.BREED_ID
     *
     * @param breedId the value for BREED_ATTR.BREED_ID
     *
     * @mbggenerated
     */
    public void setBreedId(Long breedId) {
        this.breedId = breedId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BREED_ATTR.ATTR_NAME
     *
     * @return the value of BREED_ATTR.ATTR_NAME
     *
     * @mbggenerated
     */
    public String getAttrName() {
        return attrName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BREED_ATTR.ATTR_NAME
     *
     * @param attrName the value for BREED_ATTR.ATTR_NAME
     *
     * @mbggenerated
     */
    public void setAttrName(String attrName) {
        this.attrName = attrName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BREED_ATTR.ATTR_VALUE
     *
     * @return the value of BREED_ATTR.ATTR_VALUE
     *
     * @mbggenerated
     */
    public String getAttrValue() {
        return attrValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BREED_ATTR.ATTR_VALUE
     *
     * @param attrValue the value for BREED_ATTR.ATTR_VALUE
     *
     * @mbggenerated
     */
    public void setAttrValue(String attrValue) {
        this.attrValue = attrValue;
    }
}