package com.jointown.zy.common.model;

import java.util.Date;

public class Breed extends Record {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BREED.BREED_ID
     *
     * @mbggenerated
     */
    private Long breedId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BREED.BREED_CODE
     *
     * @mbggenerated
     */
    private String breedCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BREED.BREED_NAME
     *
     * @mbggenerated
     */
    private String breedName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BREED.BREED_CNAME
     *
     * @mbggenerated
     */
    private String breedCname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BREED.BREED_COUNT_UNIT
     *
     * @mbggenerated
     */
    private String breedCountUnit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BREED.BREED_STANDARD_LEVEL
     *
     * @mbggenerated
     */
    private String breedStandardLevel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BREED.BREED_PLACE
     *
     * @mbggenerated
     */
    private String breedPlace;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BREED.CREATE_TIME
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BREED.UPDATE_TIME
     *
     * @mbggenerated
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BREED.STATUS
     *
     * @mbggenerated
     */
    private Short status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BREED.CREATER
     *
     * @mbggenerated
     */
    private Long creater;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BREED.UPDATER
     *
     * @mbggenerated
     */
    private Long updater;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BREED.BREED_EXTEND
     *
     * @mbggenerated
     */
    private String breedExtend;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BREED.BREED_ID
     *
     * @return the value of BREED.BREED_ID
     *
     * @mbggenerated
     */
    public Long getBreedId() {
        return breedId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BREED.BREED_ID
     *
     * @param breedId the value for BREED.BREED_ID
     *
     * @mbggenerated
     */
    public void setBreedId(Long breedId) {
        this.breedId = breedId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BREED.BREED_CODE
     *
     * @return the value of BREED.BREED_CODE
     *
     * @mbggenerated
     */
    public String getBreedCode() {
        return breedCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BREED.BREED_CODE
     *
     * @param breedCode the value for BREED.BREED_CODE
     *
     * @mbggenerated
     */
    public void setBreedCode(String breedCode) {
        this.breedCode = breedCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BREED.BREED_NAME
     *
     * @return the value of BREED.BREED_NAME
     *
     * @mbggenerated
     */
    public String getBreedName() {
        return breedName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BREED.BREED_NAME
     *
     * @param breedName the value for BREED.BREED_NAME
     *
     * @mbggenerated
     */
    public void setBreedName(String breedName) {
        this.breedName = breedName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BREED.BREED_CNAME
     *
     * @return the value of BREED.BREED_CNAME
     *
     * @mbggenerated
     */
    public String getBreedCname() {
        return breedCname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BREED.BREED_CNAME
     *
     * @param breedCname the value for BREED.BREED_CNAME
     *
     * @mbggenerated
     */
    public void setBreedCname(String breedCname) {
        this.breedCname = breedCname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BREED.BREED_COUNT_UNIT
     *
     * @return the value of BREED.BREED_COUNT_UNIT
     *
     * @mbggenerated
     */
    public String getBreedCountUnit() {
        return breedCountUnit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BREED.BREED_COUNT_UNIT
     *
     * @param breedCountUnit the value for BREED.BREED_COUNT_UNIT
     *
     * @mbggenerated
     */
    public void setBreedCountUnit(String breedCountUnit) {
        this.breedCountUnit = breedCountUnit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BREED.BREED_STANDARD_LEVEL
     *
     * @return the value of BREED.BREED_STANDARD_LEVEL
     *
     * @mbggenerated
     */
    public String getBreedStandardLevel() {
        return breedStandardLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BREED.BREED_STANDARD_LEVEL
     *
     * @param breedStandardLevel the value for BREED.BREED_STANDARD_LEVEL
     *
     * @mbggenerated
     */
    public void setBreedStandardLevel(String breedStandardLevel) {
        this.breedStandardLevel = breedStandardLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BREED.BREED_PLACE
     *
     * @return the value of BREED.BREED_PLACE
     *
     * @mbggenerated
     */
    public String getBreedPlace() {
        return breedPlace;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BREED.BREED_PLACE
     *
     * @param breedPlace the value for BREED.BREED_PLACE
     *
     * @mbggenerated
     */
    public void setBreedPlace(String breedPlace) {
        this.breedPlace = breedPlace;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BREED.CREATE_TIME
     *
     * @return the value of BREED.CREATE_TIME
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BREED.CREATE_TIME
     *
     * @param createTime the value for BREED.CREATE_TIME
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BREED.UPDATE_TIME
     *
     * @return the value of BREED.UPDATE_TIME
     *
     * @mbggenerated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BREED.UPDATE_TIME
     *
     * @param updateTime the value for BREED.UPDATE_TIME
     *
     * @mbggenerated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BREED.STATUS
     *
     * @return the value of BREED.STATUS
     *
     * @mbggenerated
     */
    public Short getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BREED.STATUS
     *
     * @param status the value for BREED.STATUS
     *
     * @mbggenerated
     */
    public void setStatus(Short status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BREED.CREATER
     *
     * @return the value of BREED.CREATER
     *
     * @mbggenerated
     */
    public Long getCreater() {
        return creater;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BREED.CREATER
     *
     * @param creater the value for BREED.CREATER
     *
     * @mbggenerated
     */
    public void setCreater(Long creater) {
        this.creater = creater;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BREED.UPDATER
     *
     * @return the value of BREED.UPDATER
     *
     * @mbggenerated
     */
    public Long getUpdater() {
        return updater;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BREED.UPDATER
     *
     * @param updater the value for BREED.UPDATER
     *
     * @mbggenerated
     */
    public void setUpdater(Long updater) {
        this.updater = updater;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BREED.BREED_EXTEND
     *
     * @return the value of BREED.BREED_EXTEND
     *
     * @mbggenerated
     */
    public String getBreedExtend() {
        return breedExtend;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BREED.BREED_EXTEND
     *
     * @param breedExtend the value for BREED.BREED_EXTEND
     *
     * @mbggenerated
     */
    public void setBreedExtend(String breedExtend) {
        this.breedExtend = breedExtend;
    }
}