package com.jointown.zy.common.model;

import java.util.Date;

public class BreedCategory extends Record {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BREED_CATEGORY.ID
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BREED_CATEGORY.BREED_ID
     *
     * @mbggenerated
     */
    private Long breedId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BREED_CATEGORY.CATEGORYS_ID
     *
     * @mbggenerated
     */
    private Long categorysId;
    
    private Short status;
    
    //自定义排序 按数字最大排在前面，默认为0
    private int cindex;
    
    public int getCindex() {
		return cindex;
	}

	public void setCindex(int cindex) {
		this.cindex = cindex;
	}

	public Date getCreatetime() {
		return createtime;
	}

	public void setCreatetime(Date createtime) {
		this.createtime = createtime;
	}

	//添加日期
    private Date createtime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BREED_CATEGORY.ID
     *
     * @return the value of BREED_CATEGORY.ID
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BREED_CATEGORY.ID
     *
     * @param id the value for BREED_CATEGORY.ID
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BREED_CATEGORY.BREED_ID
     *
     * @return the value of BREED_CATEGORY.BREED_ID
     *
     * @mbggenerated
     */
    public Long getBreedId() {
        return breedId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BREED_CATEGORY.BREED_ID
     *
     * @param breedId the value for BREED_CATEGORY.BREED_ID
     *
     * @mbggenerated
     */
    public void setBreedId(Long breedId) {
        this.breedId = breedId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BREED_CATEGORY.CATEGORYS_ID
     *
     * @return the value of BREED_CATEGORY.CATEGORYS_ID
     *
     * @mbggenerated
     */
    public Long getCategorysId() {
        return categorysId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BREED_CATEGORY.CATEGORYS_ID
     *
     * @param categorysId the value for BREED_CATEGORY.CATEGORYS_ID
     *
     * @mbggenerated
     */
    public void setCategorysId(Long categorysId) {
        this.categorysId = categorysId;
    }

	public Short getStatus() {
		return status;
	}

	public void setStatus(Short status) {
		this.status = status;
	}
    
    
}