package com.jointown.zy.common.model;

import java.util.Date;

public class Categorys extends Record {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CATEGORYS.ID
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CATEGORYS.CLASS_ID
     *
     * @mbggenerated
     */
    private Long classId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CATEGORYS.CATEGORYS_NAME
     *
     * @mbggenerated
     */
    private String categorysName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CATEGORYS.PARENT_ID
     *
     * @mbggenerated
     */
    private Long parentId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CATEGORYS.CATEGORYS_LEVEL
     *
     * @mbggenerated
     */
    private Short categorysLevel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CATEGORYS.CATEGORYS_ORDER
     *
     * @mbggenerated
     */
    private Long categorysOrder;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CATEGORYS.IS_LEAF
     *
     * @mbggenerated
     */
    private Short isLeaf;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CATEGORYS.CATEGORYS_PATH
     *
     * @mbggenerated
     */
    private String categorysPath;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CATEGORYS.STATUS
     *
     * @mbggenerated
     */
    private Short status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CATEGORYS.CREATE_TIME
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CATEGORYS.UPDATE_TIME
     *
     * @mbggenerated
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CATEGORYS.CREATER
     *
     * @mbggenerated
     */
    private Long creater;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CATEGORYS.UPDATER
     *
     * @mbggenerated
     */
    private Long updater;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CATEGORYS.ID
     *
     * @return the value of CATEGORYS.ID
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CATEGORYS.ID
     *
     * @param id the value for CATEGORYS.ID
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CATEGORYS.CLASS_ID
     *
     * @return the value of CATEGORYS.CLASS_ID
     *
     * @mbggenerated
     */
    public Long getClassId() {
        return classId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CATEGORYS.CLASS_ID
     *
     * @param classId the value for CATEGORYS.CLASS_ID
     *
     * @mbggenerated
     */
    public void setClassId(Long classId) {
        this.classId = classId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CATEGORYS.CATEGORYS_NAME
     *
     * @return the value of CATEGORYS.CATEGORYS_NAME
     *
     * @mbggenerated
     */
    public String getCategorysName() {
        return categorysName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CATEGORYS.CATEGORYS_NAME
     *
     * @param categorysName the value for CATEGORYS.CATEGORYS_NAME
     *
     * @mbggenerated
     */
    public void setCategorysName(String categorysName) {
        this.categorysName = categorysName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CATEGORYS.PARENT_ID
     *
     * @return the value of CATEGORYS.PARENT_ID
     *
     * @mbggenerated
     */
    public Long getParentId() {
        return parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CATEGORYS.PARENT_ID
     *
     * @param parentId the value for CATEGORYS.PARENT_ID
     *
     * @mbggenerated
     */
    public void setParentId(Long parentId) {
        this.parentId = parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CATEGORYS.CATEGORYS_LEVEL
     *
     * @return the value of CATEGORYS.CATEGORYS_LEVEL
     *
     * @mbggenerated
     */
    public Short getCategorysLevel() {
        return categorysLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CATEGORYS.CATEGORYS_LEVEL
     *
     * @param categorysLevel the value for CATEGORYS.CATEGORYS_LEVEL
     *
     * @mbggenerated
     */
    public void setCategorysLevel(Short categorysLevel) {
        this.categorysLevel = categorysLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CATEGORYS.CATEGORYS_ORDER
     *
     * @return the value of CATEGORYS.CATEGORYS_ORDER
     *
     * @mbggenerated
     */
    public Long getCategorysOrder() {
        return categorysOrder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CATEGORYS.CATEGORYS_ORDER
     *
     * @param categorysOrder the value for CATEGORYS.CATEGORYS_ORDER
     *
     * @mbggenerated
     */
    public void setCategorysOrder(Long categorysOrder) {
        this.categorysOrder = categorysOrder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CATEGORYS.IS_LEAF
     *
     * @return the value of CATEGORYS.IS_LEAF
     *
     * @mbggenerated
     */
    public Short getIsLeaf() {
        return isLeaf;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CATEGORYS.IS_LEAF
     *
     * @param isLeaf the value for CATEGORYS.IS_LEAF
     *
     * @mbggenerated
     */
    public void setIsLeaf(Short isLeaf) {
        this.isLeaf = isLeaf;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CATEGORYS.CATEGORYS_PATH
     *
     * @return the value of CATEGORYS.CATEGORYS_PATH
     *
     * @mbggenerated
     */
    public String getCategorysPath() {
        return categorysPath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CATEGORYS.CATEGORYS_PATH
     *
     * @param categorysPath the value for CATEGORYS.CATEGORYS_PATH
     *
     * @mbggenerated
     */
    public void setCategorysPath(String categorysPath) {
        this.categorysPath = categorysPath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CATEGORYS.STATUS
     *
     * @return the value of CATEGORYS.STATUS
     *
     * @mbggenerated
     */
    public Short getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CATEGORYS.STATUS
     *
     * @param status the value for CATEGORYS.STATUS
     *
     * @mbggenerated
     */
    public void setStatus(Short status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CATEGORYS.CREATE_TIME
     *
     * @return the value of CATEGORYS.CREATE_TIME
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CATEGORYS.CREATE_TIME
     *
     * @param createTime the value for CATEGORYS.CREATE_TIME
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CATEGORYS.UPDATE_TIME
     *
     * @return the value of CATEGORYS.UPDATE_TIME
     *
     * @mbggenerated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CATEGORYS.UPDATE_TIME
     *
     * @param updateTime the value for CATEGORYS.UPDATE_TIME
     *
     * @mbggenerated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CATEGORYS.CREATER
     *
     * @return the value of CATEGORYS.CREATER
     *
     * @mbggenerated
     */
    public Long getCreater() {
        return creater;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CATEGORYS.CREATER
     *
     * @param creater the value for CATEGORYS.CREATER
     *
     * @mbggenerated
     */
    public void setCreater(Long creater) {
        this.creater = creater;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CATEGORYS.UPDATER
     *
     * @return the value of CATEGORYS.UPDATER
     *
     * @mbggenerated
     */
    public Long getUpdater() {
        return updater;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CATEGORYS.UPDATER
     *
     * @param updater the value for CATEGORYS.UPDATER
     *
     * @mbggenerated
     */
    public void setUpdater(Long updater) {
        this.updater = updater;
    }
}