package com.jointown.zy.common.model;

import java.util.Date;

public class ClassInfo extends Record {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CLASS_INFO.CLASS_ID
     *
     * @mbggenerated
     */
    private Long classId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CLASS_INFO.CLASS_NAME
     *
     * @mbggenerated
     */
    private String className;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CLASS_INFO.DESCRIPTION
     *
     * @mbggenerated
     */
    private String description;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CLASS_INFO.CREATE_TIME
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CLASS_INFO.UPDATE_TIME
     *
     * @mbggenerated
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CLASS_INFO.STATUS
     *
     * @mbggenerated
     */
    private Short status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CLASS_INFO.CREATER
     *
     * @mbggenerated
     */
    private Long creater;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CLASS_INFO.UPDATER
     *
     * @mbggenerated
     */
    private Long updater;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CLASS_INFO.OPERATE_STRATE
     *
     * @mbggenerated
     */
    private String operateStrate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CLASS_INFO.CLASS_ID
     *
     * @return the value of CLASS_INFO.CLASS_ID
     *
     * @mbggenerated
     */
    public Long getClassId() {
        return classId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CLASS_INFO.CLASS_ID
     *
     * @param classId the value for CLASS_INFO.CLASS_ID
     *
     * @mbggenerated
     */
    public void setClassId(Long classId) {
        this.classId = classId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CLASS_INFO.CLASS_NAME
     *
     * @return the value of CLASS_INFO.CLASS_NAME
     *
     * @mbggenerated
     */
    public String getClassName() {
        return className;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CLASS_INFO.CLASS_NAME
     *
     * @param className the value for CLASS_INFO.CLASS_NAME
     *
     * @mbggenerated
     */
    public void setClassName(String className) {
        this.className = className;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CLASS_INFO.DESCRIPTION
     *
     * @return the value of CLASS_INFO.DESCRIPTION
     *
     * @mbggenerated
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CLASS_INFO.DESCRIPTION
     *
     * @param description the value for CLASS_INFO.DESCRIPTION
     *
     * @mbggenerated
     */
    public void setDescription(String description) {
        this.description = description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CLASS_INFO.CREATE_TIME
     *
     * @return the value of CLASS_INFO.CREATE_TIME
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CLASS_INFO.CREATE_TIME
     *
     * @param createTime the value for CLASS_INFO.CREATE_TIME
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CLASS_INFO.UPDATE_TIME
     *
     * @return the value of CLASS_INFO.UPDATE_TIME
     *
     * @mbggenerated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CLASS_INFO.UPDATE_TIME
     *
     * @param updateTime the value for CLASS_INFO.UPDATE_TIME
     *
     * @mbggenerated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CLASS_INFO.STATUS
     *
     * @return the value of CLASS_INFO.STATUS
     *
     * @mbggenerated
     */
    public Short getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CLASS_INFO.STATUS
     *
     * @param status the value for CLASS_INFO.STATUS
     *
     * @mbggenerated
     */
    public void setStatus(Short status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CLASS_INFO.CREATER
     *
     * @return the value of CLASS_INFO.CREATER
     *
     * @mbggenerated
     */
    public Long getCreater() {
        return creater;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CLASS_INFO.CREATER
     *
     * @param creater the value for CLASS_INFO.CREATER
     *
     * @mbggenerated
     */
    public void setCreater(Long creater) {
        this.creater = creater;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CLASS_INFO.UPDATER
     *
     * @return the value of CLASS_INFO.UPDATER
     *
     * @mbggenerated
     */
    public Long getUpdater() {
        return updater;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CLASS_INFO.UPDATER
     *
     * @param updater the value for CLASS_INFO.UPDATER
     *
     * @mbggenerated
     */
    public void setUpdater(Long updater) {
        this.updater = updater;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CLASS_INFO.OPERATE_STRATE
     *
     * @return the value of CLASS_INFO.OPERATE_STRATE
     *
     * @mbggenerated
     */
    public String getOperateStrate() {
        return operateStrate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CLASS_INFO.OPERATE_STRATE
     *
     * @param operateStrate the value for CLASS_INFO.OPERATE_STRATE
     *
     * @mbggenerated
     */
    public void setOperateStrate(String operateStrate) {
        this.operateStrate = operateStrate;
    }
}