package com.jointown.zy.common.model;

import java.util.Date;

public class DictInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DICT_INFO.ID
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DICT_INFO.DICT_CODE
     *
     * @mbggenerated
     */
    private String dictCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DICT_INFO.DICT_TYPE
     *
     * @mbggenerated
     */
    private String dictType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DICT_INFO.DICT_VALUE
     *
     * @mbggenerated
     */
    private String dictValue;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DICT_INFO.DICT_DESCR
     *
     * @mbggenerated
     */
    private String dictDescr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DICT_INFO.CREATER
     *
     * @mbggenerated
     */
    private Long creater;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DICT_INFO.CREATE_TIME
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DICT_INFO.UPDATER
     *
     * @mbggenerated
     */
    private Long updater;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DICT_INFO.UPDATE_TIME
     *
     * @mbggenerated
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DICT_INFO.STATUS
     *
     * @mbggenerated
     */
    private Short status;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DICT_INFO.ID
     *
     * @return the value of DICT_INFO.ID
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DICT_INFO.ID
     *
     * @param id the value for DICT_INFO.ID
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DICT_INFO.DICT_CODE
     *
     * @return the value of DICT_INFO.DICT_CODE
     *
     * @mbggenerated
     */
    public String getDictCode() {
        return dictCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DICT_INFO.DICT_CODE
     *
     * @param dictCode the value for DICT_INFO.DICT_CODE
     *
     * @mbggenerated
     */
    public void setDictCode(String dictCode) {
        this.dictCode = dictCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DICT_INFO.DICT_TYPE
     *
     * @return the value of DICT_INFO.DICT_TYPE
     *
     * @mbggenerated
     */
    public String getDictType() {
        return dictType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DICT_INFO.DICT_TYPE
     *
     * @param dictType the value for DICT_INFO.DICT_TYPE
     *
     * @mbggenerated
     */
    public void setDictType(String dictType) {
        this.dictType = dictType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DICT_INFO.DICT_VALUE
     *
     * @return the value of DICT_INFO.DICT_VALUE
     *
     * @mbggenerated
     */
    public String getDictValue() {
        return dictValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DICT_INFO.DICT_VALUE
     *
     * @param dictValue the value for DICT_INFO.DICT_VALUE
     *
     * @mbggenerated
     */
    public void setDictValue(String dictValue) {
        this.dictValue = dictValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DICT_INFO.DICT_DESCR
     *
     * @return the value of DICT_INFO.DICT_DESCR
     *
     * @mbggenerated
     */
    public String getDictDescr() {
        return dictDescr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DICT_INFO.DICT_DESCR
     *
     * @param dictDescr the value for DICT_INFO.DICT_DESCR
     *
     * @mbggenerated
     */
    public void setDictDescr(String dictDescr) {
        this.dictDescr = dictDescr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DICT_INFO.CREATER
     *
     * @return the value of DICT_INFO.CREATER
     *
     * @mbggenerated
     */
    public Long getCreater() {
        return creater;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DICT_INFO.CREATER
     *
     * @param creater the value for DICT_INFO.CREATER
     *
     * @mbggenerated
     */
    public void setCreater(Long creater) {
        this.creater = creater;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DICT_INFO.CREATE_TIME
     *
     * @return the value of DICT_INFO.CREATE_TIME
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DICT_INFO.CREATE_TIME
     *
     * @param createTime the value for DICT_INFO.CREATE_TIME
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DICT_INFO.UPDATER
     *
     * @return the value of DICT_INFO.UPDATER
     *
     * @mbggenerated
     */
    public Long getUpdater() {
        return updater;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DICT_INFO.UPDATER
     *
     * @param updater the value for DICT_INFO.UPDATER
     *
     * @mbggenerated
     */
    public void setUpdater(Long updater) {
        this.updater = updater;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DICT_INFO.UPDATE_TIME
     *
     * @return the value of DICT_INFO.UPDATE_TIME
     *
     * @mbggenerated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DICT_INFO.UPDATE_TIME
     *
     * @param updateTime the value for DICT_INFO.UPDATE_TIME
     *
     * @mbggenerated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DICT_INFO.STATUS
     *
     * @return the value of DICT_INFO.STATUS
     *
     * @mbggenerated
     */
    public Short getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DICT_INFO.STATUS
     *
     * @param status the value for DICT_INFO.STATUS
     *
     * @mbggenerated
     */
    public void setStatus(Short status) {
        this.status = status;
    }
}