DROP TABLE BOSS_ORG;
CREATE TABLE BOSS_ORG (
  ID INTEGER NOT NULL PRIMARY KEY,
  ORG_CODE VARCHAR2(100) NOT NULL ,
  ORG_NAME VARCHAR2(100) DEFAULT NULL ,
  PARENT_ID INTEGER DEFAULT NULL,
  ORG_LEVEL INTEGER DEFAULT NULL ,
  STATUS INTEGER DEFAULT 0 NOT NULL  ,
  CREATE_TIME DATE DEFAULT NULL ,
  UPDATE_TIME DATE DEFAULT NULL ,
  CONSTRAINT BOSS_ORG_UNIQUE UNIQUE(ORG_CODE)
) tablespace ZYC_DATA;
comment on table BOSS_ORG is '组织表'; 
comment on column BOSS_ORG.ORG_CODE is '组织编号'; 
comment on column BOSS_ORG.ORG_NAME is '组织编号'; 
comment on column BOSS_ORG.PARENT_ID is '父组织ID'; 
comment on column BOSS_ORG.ORG_LEVEL is '组织层级'; 
comment on column BOSS_ORG.STATUS is '状态 0:有效 1:删除'; 
comment on column BOSS_ORG.CREATE_TIME is '创建时间'; 
comment on column BOSS_ORG.UPDATE_TIME is '修改时间';
DROP SEQUENCE SEQ_BOSS_ORG;
CREATE SEQUENCE SEQ_BOSS_ORG START WITH 1 INCREMENT BY 1;

DROP TABLE BOSS_USERS;
CREATE TABLE BOSS_USERS (
  ID INTEGER NOT NULL,
  USER_CODE VARCHAR2(100) NOT NULL,
  USER_NAME VARCHAR2(100) NOT NULL,
  PASSWORD VARCHAR2(200) NOT NULL,
  SALT VARCHAR2(200) DEFAULT NULL ,
  PHONE VARCHAR2(50) DEFAULT NULL ,
  EMAIL VARCHAR2(200) DEFAULT NULL,
  ORG_ID INTEGER NOT NULL,
  STATUS INTEGER DEFAULT '0' NOT NULL,
  CREATE_TIME DATE DEFAULT NULL,
  UPDATE_TIME DATE DEFAULT NULL,
  EXPIRE_TIME DATE DEFAULT NULL,
  PRIMARY KEY (ID),
  CONSTRAINT BOSS_USERS_UNIQUE UNIQUE(USER_CODE)
) tablespace ZYC_DATA;
comment on table BOSS_USERS is '用户表'; 
comment on column BOSS_USERS.USER_CODE is '用户编号'; 
comment on column BOSS_USERS.USER_NAME is '用户名'; 
comment on column BOSS_USERS.PASSWORD is '密码'; 
comment on column BOSS_USERS.SALT is '密码盐'; 
comment on column BOSS_USERS.PHONE is '电话'; 
comment on column BOSS_USERS.EMAIL is '邮箱'; 
comment on column BOSS_USERS.ORG_ID is '组织ID'; 
comment on column BOSS_USERS.STATUS is '状态 0：有效 1：删除 2：未激活 3：锁定'; 
comment on column BOSS_USERS.CREATE_TIME is '创建时间'; 
comment on column BOSS_USERS.UPDATE_TIME is '修改时间'; 
comment on column BOSS_USERS.EXPIRE_TIME is '过期时间';
DROP SEQUENCE SEQ_BOSS_USERS;
CREATE SEQUENCE SEQ_BOSS_USERS START WITH 1 INCREMENT BY 1;


DROP TABLE BOSS_PERMISSION;
CREATE TABLE BOSS_PERMISSION (
  ID INTEGER NOT NULL,
  PERMISSION_CODE VARCHAR2(100) NOT NULL,
  PERMISSION_NAME VARCHAR2(100) NOT NULL ,
  DESCRIPTION VARCHAR2(250) DEFAULT NULL ,
  PARENT_ID INTEGER DEFAULT NULL ,
  TYPE INTEGER DEFAULT NULL ,
  OPERATION_RESOURCE VARCHAR2(250) DEFAULT NULL,
  RULE VARCHAR2(200) DEFAULT NULL,
  STATUS INTEGER DEFAULT '0' NOT NULL,
  CREATE_TIME DATE DEFAULT NULL,
  UPDATE_TIME DATE DEFAULT NULL,
  PRIMARY KEY (ID),
  CONSTRAINT PERMISSION_CODE_UNIQUE UNIQUE(PERMISSION_CODE)
) tablespace ZYC_DATA;
comment on table BOSS_PERMISSION is '权限表'; 
comment on column BOSS_PERMISSION.PERMISSION_CODE is '权限编号'; 
comment on column BOSS_PERMISSION.PERMISSION_NAME is '权限名'; 
comment on column BOSS_PERMISSION.DESCRIPTION is '描述'; 
comment on column BOSS_PERMISSION.PARENT_ID is '父权限ID'; 
comment on column BOSS_PERMISSION.TYPE is '权限类别 0:页面 1:菜单 2:按钮'; 
comment on column BOSS_PERMISSION.OPERATION_RESOURCE is '对应于不同的权限类别记录权限可以操作的资源。譬如 页面URL,menu的URL,button的标记等等'; 
comment on column BOSS_PERMISSION.RULE is '权限规则'; 
comment on column BOSS_PERMISSION.STATUS is '状态 0：有效 1：删除'; 
comment on column BOSS_PERMISSION.CREATE_TIME is '创建时间'; 
comment on column BOSS_PERMISSION.UPDATE_TIME is '修改时间';  
DROP SEQUENCE SEQ_BOSS_PERMISSION;
CREATE SEQUENCE SEQ_BOSS_PERMISSION START WITH 1 INCREMENT BY 1;


DROP TABLE BOSS_ROLE;
CREATE TABLE BOSS_ROLE (
  ID INTEGER NOT NULL,
  ROLE_CODE VARCHAR2(100) NOT NULL,
  ROLE_NAME VARCHAR2(100) NOT NULL,
  ROLE_DESCRIPTION VARCHAR2(250) DEFAULT NULL,
  STATUS VARCHAR2(45) DEFAULT '0' NOT NULL,
  CREATE_TIME DATE DEFAULT NULL,
  UPDATE_TIME DATE DEFAULT NULL,
  PRIMARY KEY (ID),
  CONSTRAINT BOSS_ROLE_UNIQUE UNIQUE (ROLE_CODE)
) tablespace ZYC_DATA;
comment on table BOSS_ROLE is '角色表'; 
comment on column BOSS_ROLE.ROLE_CODE is '角色代码'; 
comment on column BOSS_ROLE.ROLE_NAME is '角色名称'; 
comment on column BOSS_ROLE.ROLE_DESCRIPTION is '描述'; 
comment on column BOSS_ROLE.STATUS is '状态 0：有效 1：删除'; 
comment on column BOSS_ROLE.CREATE_TIME is '创建时间'; 
comment on column BOSS_ROLE.UPDATE_TIME is '修改时间';  
DROP SEQUENCE SEQ_BOSS_ROLE;
CREATE SEQUENCE SEQ_BOSS_ROLE START WITH 1 INCREMENT BY 1;


DROP TABLE BOSS_ROLE_PERMISSION;
CREATE TABLE BOSS_ROLE_PERMISSION (
  ROLE_ID INTEGER NOT NULL,
  PERMISSION_ID INTEGER NOT NULL,
  STATUS INTEGER NOT NULL,
  CREATE_TIME DATE DEFAULT NULL,
  PRIMARY KEY (ROLE_ID,PERMISSION_ID)
) tablespace ZYC_DATA;
comment on table BOSS_ROLE_PERMISSION is '角色权限关系表'; 
comment on column BOSS_ROLE_PERMISSION.ROLE_ID is '角色ID'; 
comment on column BOSS_ROLE_PERMISSION.PERMISSION_ID is '权限ID'; 
comment on column BOSS_ROLE_PERMISSION.STATUS is '状态 0：有效 1：删除'; 
comment on column BOSS_ROLE_PERMISSION.CREATE_TIME is '创建时间'; 


DROP TABLE BOSS_USER_ROLE;
CREATE TABLE BOSS_USER_ROLE (
  USER_ID INTEGER NOT NULL,
  ROLE_ID INTEGER NOT NULL,
  STATUS INTEGER NOT NULL ,
  CREATE_TIME DATE DEFAULT NULL,
  PRIMARY KEY (USER_ID,ROLE_ID)
) tablespace ZYC_DATA;
comment on table BOSS_USER_ROLE is '用户角色关系表'; 
comment on column BOSS_USER_ROLE.ROLE_ID is '角色ID'; 
comment on column BOSS_USER_ROLE.USER_ID is '用户ID'; 
comment on column BOSS_USER_ROLE.STATUS is '状态 0：有效 1：删除'; 
comment on column BOSS_USER_ROLE.CREATE_TIME is '创建时间'; 