package com.jointown.zy.common.dao;

import java.util.HashMap;
import java.util.List;

import com.jointown.zy.common.model.Breed;
import com.jointown.zy.common.model.BreedCategory;

public interface BreedCategoryDao {
	
	 /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BREED_CATEGORY
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BREED_CATEGORY
     *
     * @mbggenerated
     */
    int insert(BreedCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BREED_CATEGORY
     *
     * @mbggenerated
     */
    int insertSelective(BreedCategory record);

   
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BREED_CATEGORY
     *
     * @mbggenerated
     */
    BreedCategory selectByPrimaryKey(Long id);

   
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BREED_CATEGORY
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(BreedCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BREED_CATEGORY
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(BreedCategory record);
    
    /**
     * 后台类目自定义排序验证规则
     */
    @SuppressWarnings("rawtypes")
    public int selectRules(HashMap map);
    
    /**
	 * 功能：根据主键id修改排序规则
	 * 增加日期：2015.4.3
	 * 添加人：Mr.song
	 */
    public int updateIndex(HashMap<String,Object> map);
    
    /**
     * @author seven
     * @description 在breedCategorys中逻辑删除breed和categorys的关系
     * @param breed
     * @return
     */
    int deleteLogicByBreedId(Breed breed);
    /**
     * 
     * @param breedId
     * @return
     */
    List<BreedCategory> selectByBreedId(Long breedId);
    /**
     * 通过breedId删除BreedCategory
     * @param breedId
     * @return
     */
    int deleteBreedCategoryBybreedId(Long breedId);
}
