package com.jointown.zy.common.dao;

import java.util.List;

import com.jointown.zy.common.model.BreedAttr;

public interface BreedAttrDao {

	
	/**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BREED_ATTR
     *@param id
     *@author chengchang
     *@description 根据BreedAttr的主键进行删除(直接删除)
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BREED_ATTR
     *@param BreedAttr 
     *@author chengchang
     *@description 插入BreedAttr
     * @mbggenerated
     */
    int insert(BreedAttr record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BREED_ATTR
     *@param BreedAttr 
     *@author chengchang 
     *@description 
     * @mbggenerated
     */
    int insertSelective(BreedAttr record);


    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BREED_ATTR
     *
     * @mbggenerated
     */
    BreedAttr selectByPrimaryKey(Long id);


    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BREED_ATTR
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(BreedAttr record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BREED_ATTR
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(BreedAttr record);
    /**
     * 
     * @param breedAttrs
     * @return int
     * @description 批量插入BreedAttr标签
     */
    int insert(List <BreedAttr> breedAttrs);
    
    List <BreedAttr> queryBreedAttr (BreedAttr breedAttr);
    public int deleteBreedAttrByBreedId(long breedId);
}
