package com.jointown.zy.common.dao;

import java.util.List;

import com.jointown.zy.common.model.Categorys;

public interface CategorysDao {

	/**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CATEGORYS
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CATEGORYS
     *
     * @mbggenerated
     */
    int insert(Categorys record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CATEGORYS
     *
     * @mbggenerated
     */
    int insertSelective(Categorys record);
    
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CATEGORYS
     *
     * @mbggenerated
     */
    Categorys selectByPrimaryKey(Long id);
    
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CATEGORYS
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Categorys record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CATEGORYS
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Categorys record);
    
    //获取类目序列的下一个值
    long selectCategorysSeq();
    
    //根据查询条件获取类目信息
    List<Categorys> selectList(Categorys record);
    
    public List<Categorys> getCategorysByNameAndClassName(Long breedId);
}
