package com.jointown.zy.common.dao;

import java.util.List;

import com.jointown.zy.common.model.ClassInfo;

public interface ClassInfoDao {

	 /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CLASS_INFO
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long classId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CLASS_INFO
     *
     * @mbggenerated
     */
    int insert(ClassInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CLASS_INFO
     *
     * @mbggenerated
     */
    int insertSelective(ClassInfo record);

        /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CLASS_INFO
     *
     * @mbggenerated
     */
    ClassInfo selectByPrimaryKey(Long classId);

    
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CLASS_INFO
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(ClassInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CLASS_INFO
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(ClassInfo record);
    
    List<ClassInfo> selectList(ClassInfo record);
}
